CREATE TABLE IF NOT EXISTS fraud (
    count bigint, 
    id bigint generated by default as identity, 
    card_number varchar(255) unique, 
    status varchar(255) check (status in ('GREEN','ORANGE','RED')), 
    primary key (id)
);
