image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - "vscjava.vscode-java-pack"
    - "vscjava.vscode-gradle"

tasks:
  - name: Download Grafana OpenTelemetry Java agent
    command: bash scripts/download-agent.sh && gp sync-done agent
  - name: Execute a first gradle task
    command: ./gradlew tasks && gp sync-done gradle
  - name: Build and start all the infrastructure
    init: gp sync-await agent && gp sync-await gradle
    env:
      COMPOSE_PARALLEL_LIMIT: 1
    command: docker compose up -d --build