{
 "title": "Easypay Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_cpu_recent_utilization_ratio{service_name=\"easypay-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{service_name=\"easypay-service\"}",
     "legendFormat": "{{jvm_memory_pool_name}}"
    }
   ]
  },
  {
   "title": "Payment request count total (rated)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(easypay_payment_requests_total{service_name=\"easypay-service\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Payment Durations distribution",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(easypay_payment_process_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(easypay_payment_process_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(easypay_payment_process_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(easypay_payment_process_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(easypay_payment_process_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "999th"
    }
   ]
  },
  {
   "title": "Requests process performance",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(easypay_payment_process_milliseconds_bucket) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests store performance",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort(sum(easypay_payment_store_milliseconds_bucket) by (le))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}